# Numpy 

In [1]:
import numpy as np

In [2]:
#numpy array
arr = np.array([[1, 2, 3],
              [4, 2, 5]])

In [3]:
type(arr)
#nd - n dimensional

numpy.ndarray

In [4]:
#how many dimensions
arr.ndim 

2

In [5]:
#number of rows and columns
arr.shape

(2, 3)

In [7]:
#1D array
ar = np.array([1, 2, 3])

In [10]:
ar.ndim

1

In [11]:
ar.shape

(3,)

In [12]:
#number of elements
arr.size

6

In [13]:
#data type of the elements of the array
arr.dtype

dtype('int32')

In [15]:
#creating numpy array from list with type float
a = np.array([[1,2,3],[4,5,6]], dtype = 'float')
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
#creating array using tuple
b = np.array((1,2,3))
print(b)

[1 2 3]


In [17]:
#creating a 3X4 array with all zeros
c = np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
#create an array with random values
d = np.random.random((2,2))
print(d)

[[0.91553324 0.89853783]
 [0.84321164 0.0477857 ]]


In [19]:
#create a const value array of complex type
e = np.full((3,3), 6, dtype = 'complex')
print(e)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [20]:
#create a sequence of integers from 0 to 30 with steps of 5
f = np.arange(0,30,5)
print(f)

[ 0  5 10 15 20 25]


In [22]:
#create a sequence of 10 values in range 0 to 5
g = np.linspace(0,5,10)
print(g)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [24]:
#reshaping 3X4 array to 2X2X3 array
h = np.array([[1,2,3,4],
             [5,2,4,2],
             [1,2,0,1]])
newarr = h.reshape(2,2,3)
print(h)
print("\n")
print(newarr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]


[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [25]:
#creating a 3X4 array with all ones
c = np.ones((3,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
#flatten array
i = np.array([[1,2,3,4],
             [5,2,4,2],
             [1,2,0,1]])
flat = i.flatten()
print(flat)

[1 2 3 4 5 2 4 2 1 2 0 1]


In [28]:
#indexing
j = np.array([[1,2,3,4],
             [5,2,4,2],
             [1,2,0,1],
             [3,4,-7,8]])
j[1:,:3]

array([[ 5,  2,  4],
       [ 1,  2,  0],
       [ 3,  4, -7]])

In [29]:
#cols in steps of 2
j[1:,:3:2]

array([[ 5,  4],
       [ 1,  0],
       [ 3, -7]])

In [30]:
#rows and cols in steps of 2
#arr[strt:end+1:steps(rows), start:end+1:steps(cols)]
j[1::2,:3:2]

array([[ 5,  4],
       [ 3, -7]])

In [31]:
#conditional indexing
con = j > 0
temp = j[con]
print(temp)

[1 2 3 4 5 2 4 2 1 2 1 3 4 8]


In [33]:
ar = np.array([1, 2, 3])
#broadcasting feature
ar+1

array([2, 3, 4])

In [34]:
ar-1

array([0, 1, 2])

In [35]:
ar.T

array([1, 2, 3])

In [36]:
i = np.array([[1,2,3,4],
             [5,2,4,2],
             [1,2,0,1]])

In [37]:
#Transpose
i.T

array([[1, 5, 1],
       [2, 2, 2],
       [3, 4, 0],
       [4, 2, 1]])

In [38]:
#max element
i.max()

5

In [39]:
i.cumsum()

array([ 1,  3,  6, 10, 15, 17, 21, 23, 24, 26, 26, 27], dtype=int32)

In [41]:
#axis defines whether you want to go row wise or col wise
i.cumsum(axis = 0) #rowwise(0 for colwise)

array([[1, 2, 3, 4],
       [6, 4, 7, 6],
       [7, 6, 7, 7]], dtype=int32)

In [42]:
i.max(axis = 0)

array([5, 2, 4, 4])

# Matrix operations
a+b, a-b, a*b, a.dot(b)

can create array of sine values, exponential values and sqrt values

a = np.array([0,np.pi/2, np.pi]) np.sin(a), a = np.array ([0,1,2,3]) np.exp(a), np.sqrt(a)

In [46]:
arrs = np.array([[7,3,8],
                [1,4,9],
                [2,0,6]])
print(arrs)
np.sort(arrs, axis = 0)

[[7 3 8]
 [1 4 9]
 [2 0 6]]


array([[1, 0, 6],
       [2, 3, 8],
       [7, 4, 9]])

In [48]:
#mergesort
np.sort(arrs, axis = 1, kind = 'mergesort')

array([[3, 7, 8],
       [1, 4, 9],
       [0, 2, 6]])

In [49]:
#set alias for dtype
dtypes = [('name','S10'), ('year',int), ('cgpa', float)]
values = [('Aayushi', 2001, 10), ('Aahana', 2002, 8), ('x', 2003, 9)]
arra = np.array(values, dtype = dtypes)
print(arra)

[(b'Aayushi', 2001, 10.) (b'Aahana', 2002,  8.) (b'x', 2003,  9.)]
